Repository nanoframework/System.Device.Wifi, pull requests merged in 2021-06, with the labels that each got.

#113 Adding NetworkHelper
  NetworkHelper.nuspec
  NetworkHelper.sln
  NetworkHelper/ConnectionError.cs
  NetworkHelper/IPConfiguration.cs
  NetworkHelper/NetworkHelper.cs
  NetworkHelper/NetworkHelper.nfproj
  NetworkHelper/Properties/AssemblyInfo.cs
  NetworkHelper/key.snk
  NetworkHelper/packages.config
  README.md
  System.Threading.CancellationToken/CancellationToken.cs
  System.Threading.CancellationToken/CancellationTokenRegistration.cs
  System.Threading.CancellationToken/CancellationTokenSource.cs
  System.Threading.CancellationToken/OperationCanceledException.cs
  System.Threading.CancellationToken/System.Threading.CancellationToken.projitems
  System.Threading.CancellationToken/System.Threading.CancellationToken.shproj
  Tests/NFUnitTestWifiConnection/ConnectToWifiFixIPAddressTests.cs
  Tests/NFUnitTestWifiConnection/ConnectToWifiWithCredentialsScanTests.cs
  Tests/NFUnitTestWifiConnection/ConnectToWifiWithCredentialsTests.cs
  Tests/NFUnitTestWifiConnection/ConnectToWifiWithoutCredentialsTests.cs
  Tests/NFUnitTestWifiConnection/NFUnitTestWifiConnection.nfproj
  Tests/NFUnitTestWifiConnection/Properties/AssemblyInfo.cs
  Tests/NFUnitTestWifiConnection/nano.runsettings
  Tests/NFUnitTestWifiConnection/packages.config
  azure-pipelines.yml
Labels: Area: Config-and-Build, Type: Unit Tests, Type: dependencies, Type: enhancement

#121 Moving System.Threading from shared project to nuget
  NetworkHelper/NetworkHelper.nfproj
  NetworkHelper/packages.config
  nanoFramework.NetWorkHelper.nuspec
  nanoFramework.NetWorkHelper.sln
Labels: Type: dependencies, Type: enhancement

#122 Moving System.Threading from shared project to nuget
  NetworkHelper/NetworkHelper.nfproj
  NetworkHelper/packages.config
  System.Threading.CancellationToken/CancellationToken.cs
  System.Threading.CancellationToken/CancellationTokenRegistration.cs
  System.Threading.CancellationToken/CancellationTokenSource.cs
  System.Threading.CancellationToken/OperationCanceledException.cs
  System.Threading.CancellationToken/System.Threading.CancellationToken.projitems
  System.Threading.CancellationToken/System.Threading.CancellationToken.shproj
  Tests/NFUnitTestWifiConnection/NFUnitTestWifiConnection.nfproj
  Tests/NFUnitTestWifiConnection/packages.config
  nanoFramework.NetWorkHelper.nuspec
Labels: Type: bug

#126 Work CI-CD
  azure-pipelines.yml
Labels: Area: Config-and-Build
